name = input("Enter your name: ")
phone_number = input("Enter your phone #: ")

print(phone_number)

length = len(name)
index = name.find("D")
name = name.capitalize()
name1 = name.upper()
name2 = name.lower()
result = name.isdigit()
result1 = name.isalpha()
result2 = phone_number.count(" ")
phone_number = phone_number.replace("-", "")

print(name)
print(name)
print(name2)
print(length)
print(index)
print(result)
print(result1)
print(result2)
print(phone_number)